---
- name: Add OpenStack Servers to in memory inventory
  hosts: control_node
  gather_facts: false
  become: false
  roles:
    - openstack_inmemory_inventory

- name: Add subscription
  hosts: load_balancers,app_servers,database_servers
  gather_facts: true
  become: true
  tasks:
    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: register system and attach subs
      redhat_subscription:
        state:   present
        auto_attach: true
        activationkey: gpte-labs-rhel8
        org_id: prod

