---
# tasks file for dns_manage

- name: Insert DNS IP
  command: >-
    nmcli connection modify "System eth0"
    ipv4.ignore-auto-dns yes
    ipv4.dns 192.168.50.187
    +ipv4.dns 150.239.16.12
    +ipv4.dns 8.8.8.8
  notify: Restart NetworkManager
